-- ════════════════════════════════════════════════════════════════════
-- FASE 5 — Compras: DOBLE PASO (Pedido del taller  →  Orden de Compra)
-- ════════════════════════════════════════════════════════════════════
-- Modelo (charla 03):
--   Paso 1 · PEDIDO  = el taller dice "hay que comprar esto" (ultra simple,
--            sin precios/proveedores). Tabla nueva `compras_pedidos`.
--   Paso 2 · OC      = Compras gestiona: varios presupuestos de proveedor →
--            elige ganadora → dispara egreso. Reusa `compras_ordenes` +
--            tabla nueva `compras_oc_presupuestos`.
--   Egreso: `egresos.orden_compra_id` YA EXISTE → al elegir ganadora se crea
--            un egreso imputado al proyecto (alimenta Rent. Proyecto).
--
-- TIPOS VERIFICADOS (2026-06-08, vía PostgREST):
--   compras_ordenes.id      = BIGINT   (probe: eq('id',1) OK / uuid ERROR)
--   compras_proveedores.id  = BIGINT
--   insumos_base.id         = BIGINT
--   proyectos.id            = UUID
--   profiles.id (uid)       = UUID
--   egresos.orden_compra_id = BIGINT (ya existe; link egreso→OC)
--
-- Idempotente. Correr en el SQL editor de Supabase.
-- ════════════════════════════════════════════════════════════════════

-- ─── 1) PEDIDOS (paso 1) ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS compras_pedidos (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo            text   NOT NULL DEFAULT 'insumo' CHECK (tipo IN ('insumo','libre')),
  descripcion     text,                 -- nombre del insumo o texto libre ("qué hay que comprar")
  insumo_id       bigint,               -- ref opcional a insumos_base (tipo='insumo')
  cantidad        numeric DEFAULT 1,
  unidad          text,
  link            text,                 -- link de referencia (tipo='libre')
  proyecto_id     uuid,                 -- opcional
  categoria_gasto text,                 -- si NO hay proyecto (oficina/vehiculo/material/...)
  urgencia        text   NOT NULL DEFAULT 'normal'    CHECK (urgencia IN ('normal','urgente')),
  nota            text,
  estado          text   NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente','en_compra','comprado','cancelado')),
  orden_compra_id bigint,               -- OC que lo resuelve (paso 2) → compras_ordenes.id
  created_by      uuid,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  _deleted        boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS idx_compras_pedidos_estado   ON compras_pedidos(estado)      WHERE _deleted = false;
CREATE INDEX IF NOT EXISTS idx_compras_pedidos_proyecto ON compras_pedidos(proyecto_id);

-- ─── 2) PRESUPUESTOS DE PROVEEDOR POR OC (paso 2: multi-quote + ganadora) ───
CREATE TABLE IF NOT EXISTS compras_oc_presupuestos (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id         bigint NOT NULL,     -- → compras_ordenes.id
  proveedor_id     bigint,             -- ref opcional a compras_proveedores
  proveedor_nombre text,              -- nombre libre si no está en la lista
  monto            numeric NOT NULL DEFAULT 0,
  link             text,
  notas            text,
  es_ganadora      boolean NOT NULL DEFAULT false,
  created_at       timestamptz NOT NULL DEFAULT now(),
  _deleted         boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS idx_oc_presu_orden ON compras_oc_presupuestos(orden_id) WHERE _deleted = false;

-- ─── 3) ALTER compras_ordenes: campos del doble paso + OC autocontenida ───
ALTER TABLE compras_ordenes ADD COLUMN IF NOT EXISTS pedido_id       bigint;   -- pedido origen (opcional)
ALTER TABLE compras_ordenes ADD COLUMN IF NOT EXISTS tipo            text DEFAULT 'insumo';
ALTER TABLE compras_ordenes ADD COLUMN IF NOT EXISTS descripcion     text;
ALTER TABLE compras_ordenes ADD COLUMN IF NOT EXISTS link            text;
ALTER TABLE compras_ordenes ADD COLUMN IF NOT EXISTS cantidad        numeric;
ALTER TABLE compras_ordenes ADD COLUMN IF NOT EXISTS categoria_gasto text;
-- (el link inverso OC→egreso ya lo da egresos.orden_compra_id; no se agrega acá)

-- ─── 4) RLS (authenticated CRUD; criterio del proyecto para módulos internos) ───
ALTER TABLE compras_pedidos          ENABLE ROW LEVEL SECURITY;
ALTER TABLE compras_oc_presupuestos  ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='compras_pedidos' AND policyname='compras_pedidos_auth_all') THEN
    CREATE POLICY compras_pedidos_auth_all ON compras_pedidos
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='compras_oc_presupuestos' AND policyname='compras_oc_presu_auth_all') THEN
    CREATE POLICY compras_oc_presu_auth_all ON compras_oc_presupuestos
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ─── 5) updated_at touch en compras_pedidos ───
CREATE OR REPLACE FUNCTION fn_compras_pedidos_touch() RETURNS trigger AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS trg_compras_pedidos_touch ON compras_pedidos;
CREATE TRIGGER trg_compras_pedidos_touch BEFORE UPDATE ON compras_pedidos
  FOR EACH ROW EXECUTE FUNCTION fn_compras_pedidos_touch();

-- Verificación rápida (opcional):
-- SELECT column_name, data_type FROM information_schema.columns WHERE table_name='compras_pedidos' ORDER BY ordinal_position;
-- SELECT column_name, data_type FROM information_schema.columns WHERE table_name='compras_ordenes'  ORDER BY ordinal_position;
