-- =============================================
-- MEPEX Lobby — Inventario: Migraciones SQL
-- =============================================
-- 4 tablas nuevas + RLS + columna stock en insumos_base
-- NO EJECUTAR DIRECTAMENTE — revisar y aplicar manualmente
-- Fecha: 2026-04-05
-- =============================================

-- ─────────────────────────────────────────────
-- 1. inventario_movimientos
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS inventario_movimientos (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamptz DEFAULT now(),
    tipo        text NOT NULL CHECK (tipo IN ('entrada', 'consumo', 'transformacion', 'ajuste')),
    subtipo     text CHECK (subtipo IN ('compra', 'devolucion', 'recupero', 'ajuste_positivo', 'ajuste_negativo', 'corte', 'recorte')),
    proyecto_id uuid REFERENCES proyectos_2026(id),
    usuario     text NOT NULL,
    notas       text,
    _deleted    boolean DEFAULT false
);

-- ─────────────────────────────────────────────
-- 2. inventario_movimiento_items
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS inventario_movimiento_items (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movimiento_id   bigint NOT NULL REFERENCES inventario_movimientos(id),
    direccion       text NOT NULL CHECK (direccion IN ('entrada', 'salida')),
    item_tipo       text NOT NULL CHECK (item_tipo IN ('catalogo', 'insumo')),
    item_id         bigint NOT NULL,
    item_nombre     text,
    cantidad        numeric NOT NULL,
    unidad          text,
    created_at      timestamptz DEFAULT now()
);

-- ─────────────────────────────────────────────
-- 3. inventario_fisico_sesiones
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS inventario_fisico_sesiones (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamptz DEFAULT now(),
    fecha       date NOT NULL DEFAULT CURRENT_DATE,
    locacion_id bigint REFERENCES locaciones(id),
    responsable text NOT NULL,
    estado      text DEFAULT 'en_curso' CHECK (estado IN ('en_curso', 'cerrada')),
    notas       text,
    _deleted    boolean DEFAULT false
);

-- ─────────────────────────────────────────────
-- 4. inventario_fisico_conteo
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS inventario_fisico_conteo (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sesion_id       bigint NOT NULL REFERENCES inventario_fisico_sesiones(id),
    item_tipo       text NOT NULL CHECK (item_tipo IN ('catalogo', 'insumo')),
    item_id         bigint NOT NULL,
    item_nombre     text,
    stock_teorico   numeric,
    stock_real      numeric,
    diferencia      numeric GENERATED ALWAYS AS (stock_real - stock_teorico) STORED,
    notas           text,
    created_at      timestamptz DEFAULT now()
);

-- ─────────────────────────────────────────────
-- 5. RLS — habilitar + policies permisivas
-- ─────────────────────────────────────────────
ALTER TABLE inventario_movimientos      ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventario_movimiento_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventario_fisico_sesiones  ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventario_fisico_conteo    ENABLE ROW LEVEL SECURITY;

-- Policies SELECT
CREATE POLICY "inventario_movimientos_select"
    ON inventario_movimientos FOR SELECT TO authenticated USING (true);
CREATE POLICY "inventario_movimiento_items_select"
    ON inventario_movimiento_items FOR SELECT TO authenticated USING (true);
CREATE POLICY "inventario_fisico_sesiones_select"
    ON inventario_fisico_sesiones FOR SELECT TO authenticated USING (true);
CREATE POLICY "inventario_fisico_conteo_select"
    ON inventario_fisico_conteo FOR SELECT TO authenticated USING (true);

-- Policies INSERT
CREATE POLICY "inventario_movimientos_insert"
    ON inventario_movimientos FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "inventario_movimiento_items_insert"
    ON inventario_movimiento_items FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "inventario_fisico_sesiones_insert"
    ON inventario_fisico_sesiones FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "inventario_fisico_conteo_insert"
    ON inventario_fisico_conteo FOR INSERT TO authenticated WITH CHECK (true);

-- Policies UPDATE
CREATE POLICY "inventario_movimientos_update"
    ON inventario_movimientos FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "inventario_movimiento_items_update"
    ON inventario_movimiento_items FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "inventario_fisico_sesiones_update"
    ON inventario_fisico_sesiones FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "inventario_fisico_conteo_update"
    ON inventario_fisico_conteo FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- Policies DELETE
CREATE POLICY "inventario_movimientos_delete"
    ON inventario_movimientos FOR DELETE TO authenticated USING (true);
CREATE POLICY "inventario_movimiento_items_delete"
    ON inventario_movimiento_items FOR DELETE TO authenticated USING (true);
CREATE POLICY "inventario_fisico_sesiones_delete"
    ON inventario_fisico_sesiones FOR DELETE TO authenticated USING (true);
CREATE POLICY "inventario_fisico_conteo_delete"
    ON inventario_fisico_conteo FOR DELETE TO authenticated USING (true);

-- ─────────────────────────────────────────────
-- 6. Agregar columna stock a insumos_base
-- ─────────────────────────────────────────────
ALTER TABLE insumos_base ADD COLUMN IF NOT EXISTS stock numeric DEFAULT 0;
